### ISSUE TITLE
would you share the raw data of DADA?

### ISSUE THREAD

**Issue by YaoXinZhi** [yangkuoone/HerGePred#3]
Hi, Would you share the raw data of DADA ? like you mentioned in your code.

bp1 = 'D:\\exp\\pred_dis_gene\\DaDa\\data\\'
    bp2 = 'D:\\exp\\pred_dis_gene\\DaDa\\'
    ppi_file = 'D:\\exp\\pred_dis_gene\\data\\SP\\blab_ppi2016.txt'
    dis_sim_file = bp1 + 'hpo&orpha_dis_sim.txt'
    cv_file = 'D:\\exp\\pred_dis_gene\\data\\dis_gene_cv\\dis_gene_cv10.json'

It's helpful for my work.

**Comment by yangkuoone** [comment]
These files can be found in Dataset folder, i.e., 
     https://github.com/yangkuoone/HerGePred/tree/master/dataset
